-- =============================================================================
-- NexusCS Seed Data
-- Simulates ~6 months of platform usage (Oct 2025 - Apr 2026)
-- Run with service_role key (bypasses RLS)
-- Audit logs are auto-generated by triggers (user_id will be NULL)
-- =============================================================================

BEGIN;

-- Guard: skip if already seeded
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM roles WHERE name = 'Manager') THEN
    RAISE NOTICE 'Seed data already exists, skipping';
    RETURN;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 1. ROLES (Manager + Analyst)
-- -----------------------------------------------------------------------------

INSERT INTO roles (id, name, is_system_role) VALUES
  ('a1b2c3d4-1111-4000-a000-000000000001', 'Manager', false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'Analyst', false);

-- -----------------------------------------------------------------------------
-- 2. ROLE PERMISSIONS
-- -----------------------------------------------------------------------------

-- Manager: read + write on everything, no delete
INSERT INTO role_permissions (role_id, table_name, can_read, can_write, can_delete) VALUES
  ('a1b2c3d4-1111-4000-a000-000000000001', 'clients',              true, true, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'contracts',            true, true, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'contract_assignments', true, true, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'contract_logs',        true, true, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'collaborators',        true, true, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'tags',                 true, true, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'audit_logs',           true, false, false),
  ('a1b2c3d4-1111-4000-a000-000000000001', 'roles',                true, false, false);

-- Analyst: read-only on most, write on contract_logs
INSERT INTO role_permissions (role_id, table_name, can_read, can_write, can_delete) VALUES
  ('a1b2c3d4-2222-4000-a000-000000000002', 'clients',              true, false, false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'contracts',            true, false, false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'contract_assignments', true, false, false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'contract_logs',        true, true,  false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'collaborators',        true, false, false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'tags',                 true, false, false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'audit_logs',           true, false, false),
  ('a1b2c3d4-2222-4000-a000-000000000002', 'roles',                true, false, false);

-- -----------------------------------------------------------------------------
-- 3. COLLABORATORS (4 new team members)
-- -----------------------------------------------------------------------------

INSERT INTO collaborators (id, user_id, role_id, full_name, email, status, invite_token, expires_at) VALUES
  ('cc000001-0000-4000-a000-000000000001', NULL, 'a1b2c3d4-1111-4000-a000-000000000001',
   'Ana Costa', 'ana.costa@moicdigital.com', 'active', NULL, NULL),
  ('cc000001-0000-4000-a000-000000000002', NULL, 'a1b2c3d4-1111-4000-a000-000000000001',
   'Lucas Ferreira', 'lucas.ferreira@moicdigital.com', 'active', NULL, NULL),
  ('cc000001-0000-4000-a000-000000000003', NULL, 'a1b2c3d4-2222-4000-a000-000000000002',
   'Mariana Silva', 'mariana.silva@moicdigital.com', 'active', NULL, NULL),
  ('cc000001-0000-4000-a000-000000000004', NULL, 'a1b2c3d4-2222-4000-a000-000000000002',
   'Rafael Oliveira', 'rafael.oliveira@moicdigital.com', 'invited',
   'A7F3E1D9B2C84F60ABCD1234EFGH5678', '2026-04-18T13:00:00Z');

-- -----------------------------------------------------------------------------
-- 4. TAGS
-- -----------------------------------------------------------------------------

INSERT INTO tags (id, name) VALUES
  ('aa000001-0000-4000-a000-000000000001', 'Enterprise'),
  ('aa000001-0000-4000-a000-000000000002', 'SMB'),
  ('aa000001-0000-4000-a000-000000000003', 'Startup'),
  ('aa000001-0000-4000-a000-000000000004', 'SaaS'),
  ('aa000001-0000-4000-a000-000000000005', 'Fintech'),
  ('aa000001-0000-4000-a000-000000000006', 'E-commerce'),
  ('aa000001-0000-4000-a000-000000000007', 'Healthcare'),
  ('aa000001-0000-4000-a000-000000000008', 'High Touch');

-- -----------------------------------------------------------------------------
-- 5. CLIENTS (12 clients)
-- -----------------------------------------------------------------------------

INSERT INTO clients (id, name, status, country, city, created_at) VALUES
  -- Active clients
  ('c1000001-0000-4000-a000-000000000001', 'TechNova Solutions',   'active',   'Brazil',        'São Paulo',      '2025-10-05T10:00:00Z'),
  ('c1000001-0000-4000-a000-000000000002', 'FinPay Global',        'active',   'Brazil',        'Rio de Janeiro', '2025-10-12T14:30:00Z'),
  ('c1000001-0000-4000-a000-000000000003', 'MedVita Health',       'active',   'Brazil',        'Curitiba',       '2025-11-01T09:00:00Z'),
  ('c1000001-0000-4000-a000-000000000004', 'CloudBase Inc',        'active',   'United States', 'Austin',         '2025-11-15T16:00:00Z'),
  ('c1000001-0000-4000-a000-000000000005', 'RetailMax',            'active',   'Mexico',        'Mexico City',    '2025-12-01T11:00:00Z'),
  ('c1000001-0000-4000-a000-000000000006', 'DataStream Analytics', 'active',   'Colombia',      'Bogotá',         '2025-12-10T08:00:00Z'),
  ('c1000001-0000-4000-a000-000000000007', 'Elevate Digital',      'active',   'Brazil',        'Belo Horizonte', '2026-01-08T10:00:00Z'),
  ('c1000001-0000-4000-a000-000000000008', 'NordPay',              'active',   'Argentina',     'Buenos Aires',   '2026-01-20T13:00:00Z'),
  ('c1000001-0000-4000-a000-000000000009', 'GreenLeaf Agro',       'active',   'Brazil',        'Campinas',       '2026-02-05T09:30:00Z'),
  -- Inactive clients (churned)
  ('c1000001-0000-4000-a000-000000000010', 'QuickShip Logistics',  'inactive', 'Brazil',        'Porto Alegre',   '2025-10-20T15:00:00Z'),
  ('c1000001-0000-4000-a000-000000000011', 'BrightPath Education', 'inactive', 'Chile',         'Santiago',       '2025-11-05T10:00:00Z'),
  ('c1000001-0000-4000-a000-000000000012', 'UrbanLoft Design',     'inactive', 'Peru',          'Lima',           '2025-12-15T14:00:00Z');

-- -----------------------------------------------------------------------------
-- 6. CLIENT TAGS
-- -----------------------------------------------------------------------------

INSERT INTO client_tags (client_id, tag_id) VALUES
  -- TechNova: Enterprise, SaaS, High Touch
  ('c1000001-0000-4000-a000-000000000001', 'aa000001-0000-4000-a000-000000000001'),
  ('c1000001-0000-4000-a000-000000000001', 'aa000001-0000-4000-a000-000000000004'),
  ('c1000001-0000-4000-a000-000000000001', 'aa000001-0000-4000-a000-000000000008'),
  -- FinPay: Enterprise, Fintech
  ('c1000001-0000-4000-a000-000000000002', 'aa000001-0000-4000-a000-000000000001'),
  ('c1000001-0000-4000-a000-000000000002', 'aa000001-0000-4000-a000-000000000005'),
  -- MedVita: SMB, Healthcare
  ('c1000001-0000-4000-a000-000000000003', 'aa000001-0000-4000-a000-000000000002'),
  ('c1000001-0000-4000-a000-000000000003', 'aa000001-0000-4000-a000-000000000007'),
  -- CloudBase: Enterprise, SaaS
  ('c1000001-0000-4000-a000-000000000004', 'aa000001-0000-4000-a000-000000000001'),
  ('c1000001-0000-4000-a000-000000000004', 'aa000001-0000-4000-a000-000000000004'),
  -- RetailMax: SMB, E-commerce
  ('c1000001-0000-4000-a000-000000000005', 'aa000001-0000-4000-a000-000000000002'),
  ('c1000001-0000-4000-a000-000000000005', 'aa000001-0000-4000-a000-000000000006'),
  -- DataStream: Startup, SaaS
  ('c1000001-0000-4000-a000-000000000006', 'aa000001-0000-4000-a000-000000000003'),
  ('c1000001-0000-4000-a000-000000000006', 'aa000001-0000-4000-a000-000000000004'),
  -- Elevate: SMB, SaaS
  ('c1000001-0000-4000-a000-000000000007', 'aa000001-0000-4000-a000-000000000002'),
  ('c1000001-0000-4000-a000-000000000007', 'aa000001-0000-4000-a000-000000000004'),
  -- NordPay: Startup, Fintech
  ('c1000001-0000-4000-a000-000000000008', 'aa000001-0000-4000-a000-000000000003'),
  ('c1000001-0000-4000-a000-000000000008', 'aa000001-0000-4000-a000-000000000005'),
  -- GreenLeaf: SMB
  ('c1000001-0000-4000-a000-000000000009', 'aa000001-0000-4000-a000-000000000002'),
  -- QuickShip: SMB, E-commerce
  ('c1000001-0000-4000-a000-000000000010', 'aa000001-0000-4000-a000-000000000002'),
  ('c1000001-0000-4000-a000-000000000010', 'aa000001-0000-4000-a000-000000000006'),
  -- BrightPath: Startup
  ('c1000001-0000-4000-a000-000000000011', 'aa000001-0000-4000-a000-000000000003'),
  -- UrbanLoft: SMB
  ('c1000001-0000-4000-a000-000000000012', 'aa000001-0000-4000-a000-000000000002');

-- -----------------------------------------------------------------------------
-- 7. CONTRACTS
--    Inserted in chronological order so previous_contract_id references resolve.
--    Contracts with upsells/downsells are inserted with ORIGINAL values.
-- -----------------------------------------------------------------------------

-- === FinPay Pilot (oldest, Jul 2025) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000016',
   'c1000001-0000-4000-a000-000000000002',
   'FinPay - Pilot', 'ENDED', 'RENEWED', NULL,
   '2025-07-01', '2025-10-11', '2025-09-20', 10000.00,
   '2025-07-01T10:00:00Z');

-- === QuickShip Trial (Jul 2025) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000017',
   'c1000001-0000-4000-a000-000000000010',
   'QuickShip - Trial', 'ENDED', 'RENEWED', NULL,
   '2025-07-15', '2025-10-19', '2025-10-01', 3000.00,
   '2025-07-15T12:00:00Z');

-- === TechNova Q4 2025: ENDED (RENEWED) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000001',
   'c1000001-0000-4000-a000-000000000001',
   'TechNova - Q4 2025', 'ENDED', 'RENEWED', NULL,
   '2025-10-05', '2025-12-31', '2025-12-15', 8000.00,
   '2025-10-05T10:30:00Z');

-- === FinPay H2 2025: ENDED (RENEWED), points to Pilot ===
-- Inserted with original value 15000 (upsell to 18000 happens in logs)
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000004',
   'c1000001-0000-4000-a000-000000000002',
   'FinPay - H2 2025', 'ENDED', 'RENEWED',
   'c0000001-0000-4000-a000-000000000016',
   '2025-10-12', '2026-01-31', '2026-01-15', 15000.00,
   '2025-10-12T15:00:00Z');

-- === QuickShip Logistics: ENDED (CHURN), points to Trial ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000013',
   'c1000001-0000-4000-a000-000000000010',
   'QuickShip - Logistics Plan', 'ENDED', 'CHURN',
   'c0000001-0000-4000-a000-000000000017',
   '2025-10-20', '2026-01-20', NULL, 5000.00,
   '2025-10-20T15:30:00Z');

-- === MedVita: ACTIVE, inserted with original value 8000 (downsell to 6500 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000006',
   'c1000001-0000-4000-a000-000000000003',
   'MedVita - Annual 2026', 'ACTIVE', NULL, NULL,
   '2025-11-01', '2026-10-31', '2026-09-15', 8000.00,
   '2025-11-01T09:30:00Z');

-- === BrightPath: ENDED (NOT_RENEWED) ===
-- renewal_date represents when renewal was due, not when it happened
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000014',
   'c1000001-0000-4000-a000-000000000011',
   'BrightPath - Education Suite', 'ENDED', 'NOT_RENEWED', NULL,
   '2025-11-05', '2026-02-05', '2026-01-20', 4000.00,
   '2025-11-05T10:30:00Z');

-- === CloudBase: ACTIVE, inserted with original value 20000 (upsell to 25000 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000007',
   'c1000001-0000-4000-a000-000000000004',
   'CloudBase - Enterprise Plan', 'ACTIVE', NULL, NULL,
   '2025-11-15', '2026-11-14', '2026-10-01', 20000.00,
   '2025-11-15T16:30:00Z');

-- === RetailMax: ACTIVE, inserted with original value 6000 (downsell to 4500 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000008',
   'c1000001-0000-4000-a000-000000000005',
   'RetailMax - Growth', 'ACTIVE', NULL, NULL,
   '2025-12-01', '2026-05-31', '2026-05-01', 6000.00,
   '2025-12-01T11:30:00Z');

-- === DataStream: ACTIVE, inserted with original value 2000 (upsell to 3000 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000009',
   'c1000001-0000-4000-a000-000000000006',
   'DataStream - Starter', 'ACTIVE', NULL, NULL,
   '2025-12-10', '2026-06-10', '2026-05-15', 2000.00,
   '2025-12-10T08:30:00Z');

-- === UrbanLoft: ENDED (CUT) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000015',
   'c1000001-0000-4000-a000-000000000012',
   'UrbanLoft - Design Platform', 'ENDED', 'CUT', NULL,
   '2025-12-15', '2026-06-15', NULL, 3500.00,
   '2025-12-15T14:30:00Z');

-- === TechNova Q1 2026: ENDED (RENEWED), inserted with original 10000 (upsell to 12000 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000002',
   'c1000001-0000-4000-a000-000000000001',
   'TechNova - Q1 2026', 'ENDED', 'RENEWED',
   'c0000001-0000-4000-a000-000000000001',
   '2026-01-01', '2026-03-31', '2026-03-15', 10000.00,
   '2025-12-20T09:00:00Z');

-- === Elevate: ACTIVE, inserted with original value 4000 (upsell to 5500 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000010',
   'c1000001-0000-4000-a000-000000000007',
   'Elevate - Pro Plan', 'ACTIVE', NULL, NULL,
   '2026-01-08', '2026-07-08', '2026-06-15', 4000.00,
   '2026-01-08T10:30:00Z');

-- === NordPay: ACTIVE, inserted with original value 5000 (upsell to 7000 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000011',
   'c1000001-0000-4000-a000-000000000008',
   'NordPay - Fintech Bundle', 'ACTIVE', NULL, NULL,
   '2026-01-20', '2026-07-20', '2026-06-20', 5000.00,
   '2026-01-20T13:30:00Z');

-- === FinPay 2026: ACTIVE, points to H2 2025 ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000005',
   'c1000001-0000-4000-a000-000000000002',
   'FinPay - 2026', 'ACTIVE', NULL,
   'c0000001-0000-4000-a000-000000000004',
   '2026-02-01', '2026-07-31', '2026-07-01', 18000.00,
   '2026-01-20T11:00:00Z');

-- === GreenLeaf: ACTIVE, inserted with original value 2500 (upsell to 3500 in logs) ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000012',
   'c1000001-0000-4000-a000-000000000009',
   'GreenLeaf - Agro Digital', 'ACTIVE', NULL, NULL,
   '2026-02-05', '2026-08-05', '2026-07-01', 2500.00,
   '2026-02-05T09:45:00Z');

-- === TechNova Q2 2026: ACTIVE, points to Q1 2026 ===
INSERT INTO contracts (id, client_id, name, status, termination_reason, previous_contract_id, start_date, end_date, renewal_date, current_value, created_at) VALUES
  ('c0000001-0000-4000-a000-000000000003',
   'c1000001-0000-4000-a000-000000000001',
   'TechNova - Q2 2026', 'ACTIVE', NULL,
   'c0000001-0000-4000-a000-000000000002',
   '2026-04-01', '2026-06-30', '2026-06-15', 12000.00,
   '2026-03-20T10:00:00Z');

-- -----------------------------------------------------------------------------
-- 8. CONTRACT LOGS (financial history over ~6 months)
--    Chronological order. After each upsell/downsell, UPDATE current_value.
-- -----------------------------------------------------------------------------

-- Auth user IDs used for created_by:
-- Pedro Melo:   80edd4ef-047d-4429-b543-d4aff17e8aa5
-- System Admin: fcbfe33d-fed0-422a-a06f-58ec3e38dc48

-- --- Oct 2025: FinPay Pilot → H2 renewal ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000016', 'RENEWAL_EXIT',  10000.00, 0.00,     -10000.00, '2025-10-10T10:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48'),
  ('c0000001-0000-4000-a000-000000000004', 'RENEWAL_ENTRY', 0.00,     15000.00,  15000.00,  '2025-10-10T10:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');

-- --- Oct 2025: QuickShip Trial → Logistics renewal ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000017', 'RENEWAL_EXIT',  3000.00, 0.00,    -3000.00, '2025-10-18T10:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48'),
  ('c0000001-0000-4000-a000-000000000013', 'RENEWAL_ENTRY', 0.00,    5000.00,  5000.00,  '2025-10-18T10:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');

-- --- Dec 2025: FinPay upsell 15000 → 18000 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000004', 'UPSELL', 15000.00, 18000.00, 3000.00, '2025-12-05T11:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');
UPDATE contracts SET current_value = 18000.00 WHERE id = 'c0000001-0000-4000-a000-000000000004';

-- --- Dec 2025: TechNova Q4 → Q1 renewal ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000001', 'RENEWAL_EXIT',  8000.00,  0.00,     -8000.00,  '2025-12-28T10:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5'),
  ('c0000001-0000-4000-a000-000000000002', 'RENEWAL_ENTRY', 0.00,     10000.00,  10000.00,  '2025-12-28T10:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');

-- --- Jan 2026: MedVita downsell 8000 → 6500 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000006', 'DOWNSELL', 8000.00, 6500.00, -1500.00, '2026-01-15T09:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');
UPDATE contracts SET current_value = 6500.00 WHERE id = 'c0000001-0000-4000-a000-000000000006';

-- --- Jan 2026: QuickShip CHURN ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000013', 'CHURN', 5000.00, 0.00, -5000.00, '2026-01-18T16:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');

-- --- Jan 2026: FinPay H2 → 2026 renewal ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000004', 'RENEWAL_EXIT',  18000.00, 0.00,     -18000.00, '2026-01-28T09:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5'),
  ('c0000001-0000-4000-a000-000000000005', 'RENEWAL_ENTRY', 0.00,     18000.00,  18000.00,  '2026-01-28T09:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');

-- --- Feb 2026: BrightPath NOT_RENEWED ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000014', 'NOT_RENEWED', 4000.00, 0.00, -4000.00, '2026-02-03T10:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');

-- --- Feb 2026: TechNova upsell 10000 → 12000 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000002', 'UPSELL', 10000.00, 12000.00, 2000.00, '2026-02-15T14:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');
UPDATE contracts SET current_value = 12000.00 WHERE id = 'c0000001-0000-4000-a000-000000000002';

-- --- Feb 2026: CloudBase upsell 20000 → 25000 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000007', 'UPSELL', 20000.00, 25000.00, 5000.00, '2026-02-20T15:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');
UPDATE contracts SET current_value = 25000.00 WHERE id = 'c0000001-0000-4000-a000-000000000007';

-- --- Mar 2026: DataStream upsell 2000 → 3000 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000009', 'UPSELL', 2000.00, 3000.00, 1000.00, '2026-03-01T08:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');
UPDATE contracts SET current_value = 3000.00 WHERE id = 'c0000001-0000-4000-a000-000000000009';

-- --- Mar 2026: Elevate upsell 4000 → 5500 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000010', 'UPSELL', 4000.00, 5500.00, 1500.00, '2026-03-05T13:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');
UPDATE contracts SET current_value = 5500.00 WHERE id = 'c0000001-0000-4000-a000-000000000010';

-- --- Mar 2026: RetailMax downsell 6000 → 4500 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000008', 'DOWNSELL', 6000.00, 4500.00, -1500.00, '2026-03-10T10:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');
UPDATE contracts SET current_value = 4500.00 WHERE id = 'c0000001-0000-4000-a000-000000000008';

-- --- Mar 2026: NordPay upsell 5000 → 7000 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000011', 'UPSELL', 5000.00, 7000.00, 2000.00, '2026-03-15T14:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');
UPDATE contracts SET current_value = 7000.00 WHERE id = 'c0000001-0000-4000-a000-000000000011';

-- --- Mar 2026: UrbanLoft CUT ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000015', 'CUT', 3500.00, 0.00, -3500.00, '2026-03-20T11:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');

-- --- Mar 2026: GreenLeaf upsell 2500 → 3500 ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000012', 'UPSELL', 2500.00, 3500.00, 1000.00, '2026-03-25T10:00:00Z', 'fcbfe33d-fed0-422a-a06f-58ec3e38dc48');
UPDATE contracts SET current_value = 3500.00 WHERE id = 'c0000001-0000-4000-a000-000000000012';

-- --- Mar 2026: TechNova Q1 → Q2 renewal ---
INSERT INTO contract_logs (contract_id, action_type, old_value, new_value, delta_value, created_at, created_by) VALUES
  ('c0000001-0000-4000-a000-000000000002', 'RENEWAL_EXIT',  12000.00, 0.00,     -12000.00, '2026-03-28T09:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5'),
  ('c0000001-0000-4000-a000-000000000003', 'RENEWAL_ENTRY', 0.00,     12000.00,  12000.00,  '2026-03-28T09:00:00Z', '80edd4ef-047d-4429-b543-d4aff17e8aa5');

-- -----------------------------------------------------------------------------
-- 9. CONTRACT ASSIGNMENTS (team allocated to contracts)
-- -----------------------------------------------------------------------------

-- Collaborator IDs:
-- Pedro Melo:      8c2ca39f-0246-484f-bf98-f9c59828e1e1
-- Ana Costa:       cc000001-0000-4000-a000-000000000001
-- Lucas Ferreira:  cc000001-0000-4000-a000-000000000002
-- Mariana Silva:   cc000001-0000-4000-a000-000000000003

INSERT INTO contract_assignments (contract_id, collaborator_id, role_on_contract, start_date, end_date, allocation_percentage) VALUES
  -- TechNova Q4 2025 (ended)
  ('c0000001-0000-4000-a000-000000000001', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2025-10-05', '2025-12-31', 60.00),
  ('c0000001-0000-4000-a000-000000000001', 'cc000001-0000-4000-a000-000000000003', 'CS Analyst',         '2025-10-05', '2025-12-31', 30.00),

  -- TechNova Q1 2026 (ended)
  ('c0000001-0000-4000-a000-000000000002', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2026-01-01', '2026-03-31', 60.00),
  ('c0000001-0000-4000-a000-000000000002', 'cc000001-0000-4000-a000-000000000003', 'CS Analyst',         '2026-01-01', '2026-03-31', 30.00),

  -- TechNova Q2 2026 (active)
  ('c0000001-0000-4000-a000-000000000003', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2026-04-01', NULL, 50.00),
  ('c0000001-0000-4000-a000-000000000003', 'cc000001-0000-4000-a000-000000000003', 'CS Analyst',         '2026-04-01', NULL, 30.00),
  ('c0000001-0000-4000-a000-000000000003', 'cc000001-0000-4000-a000-000000000002', 'Technical Lead',     '2026-04-01', NULL, 20.00),

  -- FinPay 2026 (active)
  ('c0000001-0000-4000-a000-000000000005', 'cc000001-0000-4000-a000-000000000002', 'Account Manager',    '2026-02-01', NULL, 50.00),
  ('c0000001-0000-4000-a000-000000000005', '8c2ca39f-0246-484f-bf98-f9c59828e1e1', 'Executive Sponsor',  '2026-02-01', NULL, 10.00),

  -- MedVita (active)
  ('c0000001-0000-4000-a000-000000000006', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2025-11-01', NULL, 40.00),
  ('c0000001-0000-4000-a000-000000000006', 'cc000001-0000-4000-a000-000000000003', 'CS Analyst',         '2025-11-15', NULL, 25.00),

  -- CloudBase (active, high touch)
  ('c0000001-0000-4000-a000-000000000007', 'cc000001-0000-4000-a000-000000000002', 'Account Manager',    '2025-11-15', NULL, 60.00),
  ('c0000001-0000-4000-a000-000000000007', 'cc000001-0000-4000-a000-000000000001', 'CS Lead',            '2025-11-15', NULL, 30.00),
  ('c0000001-0000-4000-a000-000000000007', '8c2ca39f-0246-484f-bf98-f9c59828e1e1', 'Executive Sponsor',  '2025-11-15', NULL, 10.00),

  -- RetailMax (active)
  ('c0000001-0000-4000-a000-000000000008', 'cc000001-0000-4000-a000-000000000003', 'Account Manager',    '2025-12-01', NULL, 50.00),

  -- DataStream (active)
  ('c0000001-0000-4000-a000-000000000009', 'cc000001-0000-4000-a000-000000000003', 'Account Manager',    '2025-12-10', NULL, 40.00),

  -- Elevate (active)
  ('c0000001-0000-4000-a000-000000000010', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2026-01-08', NULL, 40.00),

  -- NordPay (active)
  ('c0000001-0000-4000-a000-000000000011', 'cc000001-0000-4000-a000-000000000002', 'Account Manager',    '2026-01-20', NULL, 40.00),
  ('c0000001-0000-4000-a000-000000000011', 'cc000001-0000-4000-a000-000000000003', 'CS Analyst',         '2026-02-01', NULL, 20.00),

  -- GreenLeaf (active)
  ('c0000001-0000-4000-a000-000000000012', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2026-02-05', NULL, 30.00),

  -- QuickShip (ended assignments)
  ('c0000001-0000-4000-a000-000000000013', 'cc000001-0000-4000-a000-000000000002', 'Account Manager',    '2025-10-20', '2026-01-18', 50.00),
  ('c0000001-0000-4000-a000-000000000013', 'cc000001-0000-4000-a000-000000000003', 'CS Analyst',         '2025-10-20', '2026-01-18', 25.00),

  -- BrightPath (ended)
  ('c0000001-0000-4000-a000-000000000014', 'cc000001-0000-4000-a000-000000000001', 'Account Manager',    '2025-11-05', '2026-02-03', 40.00),

  -- UrbanLoft (ended, cut early)
  ('c0000001-0000-4000-a000-000000000015', 'cc000001-0000-4000-a000-000000000003', 'Account Manager',    '2025-12-15', '2026-03-20', 40.00);

COMMIT;

-- =============================================================================
-- DONE. Audit logs are auto-generated by triggers.
-- Summary:
--   2 new roles, 16 role permissions
--   4 new collaborators (3 active, 1 invited with token)
--   8 tags, 22 client-tag links
--   12 new clients (9 active, 3 inactive)
--   17 new contracts (3 renewal chains, 9 ACTIVE, 8 ENDED)
--   24 contract logs + 8 value UPDATEs to keep current_value in sync
--   24 contract assignments
-- =============================================================================
